version: '3.4'

services:

  gateway:
    image: gateway
    container_name: gateway
    restart: always
    ports:
      - 8080:8080
    environment:
      USER_SERVICE: http://user_service:8001
      CONTENT_SERVICE: http://content_service:8002
      RECOMMENDATION_SERVICE: http://recommendation_service:8005

  frontend:
    image: frontend
    container_name: frontend
    ports:
      - 3000:3000
    environment:
      REACT_APP_CHECK: docker-compose
      REACT_APP_USER_SERVICE: http://localhost:8080/api/users
      REACT_APP_CONTENT_SERVICE: http://localhost:8080/api/content
      REACT_APP_CHAT_SERVICE: http://localhost:8080/api/chat
      REACT_APP_AGENT_SERVICE: http://localhost:8080/api/agent
      REACT_APP_RECOMMENDATION_SERVICE: http://localhost:8080/api/followers
    depends_on:
      - gateway

  neo4j:
    image: neo4j
    container_name: neo4j
    restart: always
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      NEO4J_AUTH: neo4j/root
      NEO4J_dbms_default__database: neo4j
      NEO4J_dbms_connector_bolt_advertised__address: neo4j:7687

  recommendation_service:
    image: recommendation_service
    container_name: recommendation_service
    restart: always
    environment:
      Docker_env: env
      DB_HOST: bolt://neo4j:7687
      DB_NAME: neo4j
      DB_PW: root
    ports:
      - 8005:8005
      - 8095:8095
    depends_on:
      - neo4j

  postgres:
    image: postgres
    container_name: postgres
    volumes:
      - ./pg-init-scripts:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: postgres
      POSTGRES_MULTIPLE_DATABASES: xws_users_service, xws_content_service

  user_service:
    image: user_service
    container_name: user_service
    environment:
      Docker_env: env
      DB_HOST: postgres
      DB_NAME: xws_users_service
      DB_USER: postgres
      DB_PW: root
    ports:
      - 8001:8001
      - 8091:8091
    depends_on:
      - postgres

  content_service:
    image: content_service
    container_name: content_service
    environment:
      Docker_env: env
      DB_HOST: postgres
      DB_NAME: xws_content_service
      DB_USER: postgres
      DB_PW: root
    ports:
      - 8002:8002
      - 8092:8092
    depends_on:
      - user_service

