// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PrivacyClient is the client API for Privacy service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PrivacyClient interface {
	CreatePrivacy(ctx context.Context, in *CreatePrivacyRequest, opts ...grpc.CallOption) (*EmptyResponsePrivacy, error)
	UpdatePrivacy(ctx context.Context, in *CreatePrivacyRequest, opts ...grpc.CallOption) (*EmptyResponsePrivacy, error)
}

type privacyClient struct {
	cc grpc.ClientConnInterface
}

func NewPrivacyClient(cc grpc.ClientConnInterface) PrivacyClient {
	return &privacyClient{cc}
}

func (c *privacyClient) CreatePrivacy(ctx context.Context, in *CreatePrivacyRequest, opts ...grpc.CallOption) (*EmptyResponsePrivacy, error) {
	out := new(EmptyResponsePrivacy)
	err := c.cc.Invoke(ctx, "/proto.Privacy/CreatePrivacy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privacyClient) UpdatePrivacy(ctx context.Context, in *CreatePrivacyRequest, opts ...grpc.CallOption) (*EmptyResponsePrivacy, error) {
	out := new(EmptyResponsePrivacy)
	err := c.cc.Invoke(ctx, "/proto.Privacy/UpdatePrivacy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PrivacyServer is the server API for Privacy service.
// All implementations must embed UnimplementedPrivacyServer
// for forward compatibility
type PrivacyServer interface {
	CreatePrivacy(context.Context, *CreatePrivacyRequest) (*EmptyResponsePrivacy, error)
	UpdatePrivacy(context.Context, *CreatePrivacyRequest) (*EmptyResponsePrivacy, error)
	mustEmbedUnimplementedPrivacyServer()
}

// UnimplementedPrivacyServer must be embedded to have forward compatible implementations.
type UnimplementedPrivacyServer struct {
}

func (UnimplementedPrivacyServer) CreatePrivacy(context.Context, *CreatePrivacyRequest) (*EmptyResponsePrivacy, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePrivacy not implemented")
}
func (UnimplementedPrivacyServer) UpdatePrivacy(context.Context, *CreatePrivacyRequest) (*EmptyResponsePrivacy, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePrivacy not implemented")
}
func (UnimplementedPrivacyServer) mustEmbedUnimplementedPrivacyServer() {}

// UnsafePrivacyServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PrivacyServer will
// result in compilation errors.
type UnsafePrivacyServer interface {
	mustEmbedUnimplementedPrivacyServer()
}

func RegisterPrivacyServer(s grpc.ServiceRegistrar, srv PrivacyServer) {
	s.RegisterService(&Privacy_ServiceDesc, srv)
}

func _Privacy_CreatePrivacy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePrivacyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivacyServer).CreatePrivacy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Privacy/CreatePrivacy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivacyServer).CreatePrivacy(ctx, req.(*CreatePrivacyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Privacy_UpdatePrivacy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePrivacyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivacyServer).UpdatePrivacy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Privacy/UpdatePrivacy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivacyServer).UpdatePrivacy(ctx, req.(*CreatePrivacyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Privacy_ServiceDesc is the grpc.ServiceDesc for Privacy service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Privacy_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Privacy",
	HandlerType: (*PrivacyServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePrivacy",
			Handler:    _Privacy_CreatePrivacy_Handler,
		},
		{
			MethodName: "UpdatePrivacy",
			Handler:    _Privacy_UpdatePrivacy_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "privacy.proto",
}
